replicaCount: 3

image:
  repository: vyomnetra/ssa-platform
  pullPolicy: IfNotPresent
  tag: "1.0.0"

service:
  type: ClusterIP
  port: 8000

ingress:
  enabled: true
  className: "nginx"
  hosts:
    - host: vyomnetra.local
      paths:
        - path: /
          pathType: Prefix

resources:
  limits:
    cpu: 2000m
    memory: 2Gi
  requests:
    cpu: 500m
    memory: 512Mi
